gains:
  pos: {x: 1.5, y: 1.5, z: 8.0}
  vel: {x: 1.5, y: 1.5, z: 3.0}
  ki: {x: 0.2, y: 0.2, z: 0.05, yaw: 0.02}
  kib: {x: 0.00, y: 0.00, z: 0.00}
  rot: {x: 2.5, y: 2.5, z: 1.0}
  ang: {x: 0.3, y: 0.3, z: 0.1}

corrections:
  kf: 0.0e-08
  r: 0.0
  p: 0.0

max_pos_int:   0.5
max_pos_int_b: 0.5
